const COLORS = {
  ICONS_COLOR: "#989DBC",
  BACKGROUND_COLOR_MAIN: "#F8FAFF",
  BACKGROUND_COLOR_SECONDARY: "#002687",
  CARD_BACKGROUND_COLOR: "#FFFFFF",
  TEXT_COLOR_SECONDARY: "#202B4F",
  TEXT_COLOR_SECONDARY_LIGHTER: "#8090BC",
  BAR_BACKGROUND: "#E9EAF8",
  ADD_BUTTON_BACKGROUND: "#0669FF",
  ADD_BUTTON_PLUS_COLOR: "#ffffff",
};

export default COLORS;
